### ISSUE TITLE
Memory leak in Docker container after processing an image

### ISSUE THREAD

**Issue by siddarthreddygsr** [mrhan1993/Fooocus-API#141]
I am hosting the docker container by following the steps in the README 
`
 docker run --gpus=all -e NVIDIA_DRIVER_CAPABILITIES=compute,utility -e NVIDIA_VISIBLE_DEVICES=all -p 8888:8888 konies 
`
but when I make an API call like this 

```py
import requests
import mimetypes
from maskgen import generate_mask


def get_content_type(filename):
    return mimetypes.guess_type(filename)[0] or 'application/octet-stream'

def post_image_inpaint_outpaint(input_image_path, input_mask_path):
    url = 'http://127.0.0.1:8888/v1/generation/image-inpait-outpaint'
    files = {
        'sharpness': (None, '2'),
        'input_mask': (input_mask_path, open(input_mask_path, 'rb'), get_content_type(input_mask_path)),
        'outpaint_distance_right': (None, '0'),
        'loras': (None, '[{"model_name":"sd_xl_offset_example-lora_1.0.safetensors","weight":0.1}]'),
        'outpaint_distance_left': (None, '0'),
        'advanced_params': (None, ''),
        'guidance_scale': (None, '4'),
        'prompt': (None, 'A serene landscape with rolling green hills under a clear blue sky.'),
        'input_image': (input_image_path, open(input_image_path, 'rb'), get_content_type(input_image_path)),
        'outpaint_distance_bottom': (None, '0'),
        'require_base64': (None, 'false'),
        'async_process': (None, 'false'),
        'image_number': (None, '1'),
        'negative_prompt': (None, 'No buildings, people, or animals. Avoid dark, gloomy weather.'),
        'refiner_switch': (None, '0.5'),
        'base_model_name': (None, 'juggernautXL_version6Rundiffusion.safetensors'),
        'image_seed': (None, "-1"),
        'style_selections': (None, 'Fooocus V2,Fooocus Enhance,Fooocus Sharp'),
        'inpaint_additional_prompt': (None, ''),
        'outpaint_selections': (None, ''),
        'outpaint_distance_top': (None, '0'),
        'refiner_model_name': (None, 'None'),
        'aspect_ratios_selection': (None, '1152*896'),
        'performance_selection': (None, 'Speed'),
    }
    
    response = requests.post(url, files=files)
    return response

input_image_path = '1.jpg'
input_mask_path = "mask.jpg"
response = post_image_inpaint_outpaint(input_image_path, input_mask_path)

if response.ok:
    print("Success:", response.json())
else:
    print("Error:", response.status_code, response.text)
```

it works fine for the first image but after the first image is generated the system RAM is almost full and it when I run it on a second image it overflows the memory and crashes the system.

<img width="1920" alt="image" src="https://github.com/konieshadow/Fooocus-API/assets/73605274/09d13f21-66a6-4527-8a12-b568633d3b17">

**Comment by siddarthreddygsr** [comment]
The same code gives me this error when I run make an API call

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/ubuntu/api/Fooocus-API/fooocusapi/api.py", line 168, in img_inpaint_or_outpaint
    return generation_output(results, streaming_output, req.require_base64)
  File "/home/ubuntu/api/Fooocus-API/fooocusapi/api_utils.py", line 196, in generation_output
    results = [GeneratedImageResult(
  File "/home/ubuntu/api/Fooocus-API/fooocusapi/api_utils.py", line 196, in <listcomp>
    results = [GeneratedImageResult(
  File "/home/ubuntu/anaconda3/envs/fooocus-api/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for GeneratedImageResult
seed
  Input should be a valid string [type=string_type, input_value=2386915002891312687, input_type=int]
    For further information visit https://errors.pydantic.dev/2.4/v/string_type
```

**Comment by mrhan1993** [comment]
increase your swap memory or use -m flay to limit container usage
```shell
docker run --gpus=all \
    -m 8192m \
    -e NVIDIA_DRIVER_CAPABILITIES=compute,utility \
    -e NVIDIA_VISIBLE_DEVICES=all -p 8888:8888 konies 
```
