### ISSUE TITLE
Error when deploying to replicate

### ISSUE THREAD

**Issue by platform-kit** [mrhan1993/Fooocus-API#323]
Hi there. I'm getting the following error when running `cog build` (before deploying to Replicaate)

```
Validating model schema...

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/.pyenv/versions/3.11.9/lib/python3.11/site-packages/cog/command/openapi_schema.py", line 21, in <module>
    raise CogError(app.state.setup_result.logs)
cog.errors.CogError: Error while loading predictor:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.11.9/lib/python3.11/site-packages/cog/server/http.py", line 131, in create_app
    predictor = load_predictor_from_ref(predictor_ref)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.9/lib/python3.11/site-packages/cog/predictor.py", line 184, in load_predictor_from_ref
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/predict.py", line 29, in <module>
    from fooocusapi.parameters import ImageGenerationParams
  File "/src/fooocusapi/parameters.py", line 5, in <module>
    from fooocusapi.models.common.requests import AdvancedParams
  File "/src/fooocusapi/models/common/requests.py", line 9, in <module>
    from modules.config import (
ModuleNotFoundError: No module named 'modules'
```

Any tips?  Not sure why "modules" is not registering.

**Comment by mrhan1993** [comment]
use tag v0.4.0.3 , it is work well

**Comment by mrhan1993** [comment]
try branch `cog-main`
