### ISSUE TITLE
Hey, I'm getting this problem

### ISSUE THREAD

**Issue by annie-bhaiya** [mrhan1993/Fooocus-API#357]
Exception in thread Thread-3 (task_schedule_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/azureuser/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/azureuser/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/azureuser/sturdy-octo-carnival/fooocusapi/worker.py", line 36, in task_schedule_loop
    process_generate(current_task)
  File "/home/azureuser/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/azureuser/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/azureuser/sturdy-octo-carnival/fooocusapi/worker.py", line 83, in process_generate
    from modules.sdxl_styles import apply_style, fooocus_expansion, apply_wildcards
ImportError: cannot import name 'apply_wildcards' from 'modules.sdxl_styles' (/home/azureuser/sturdy-octo-carnival/repositories/Fooocus/modules/sdxl_styles.py)

**Comment by mrhan1993** [comment]
It seems that your API and Fooocus versions are not compatible.
I suggest you synchronize the code with the code in the repository
