### ISSUE TITLE
Bug task stuck, must be restarted to recover

### ISSUE THREAD

**Issue by 812913329** [mrhan1993/Fooocus-API#38]
Traceback (most recent call last):
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\fastapi\routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "G:\ai\codu1\envs\fooocus-api\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\ai\Fooocus-API-main\Fooocus\fooocusapi\api.py", line 89, in text2img_generation
    return generation_output(results, streaming_output, req.require_base64)
  File "F:\ai\Fooocus-API-main\Fooocus\fooocusapi\api_utils.py", line 139, in generation_output
    results = [GeneratedImageResult(
  File "F:\ai\Fooocus-API-main\Fooocus\fooocusapi\api_utils.py", line 142, in <listcomp>
    url=get_file_serve_url(item.im),
  File "F:\ai\Fooocus-API-main\Fooocus\fooocusapi\file_utils.py", line 54, in get_file_serve_url
    return static_serve_base_url + filename
TypeError: can only concatenate str (not "NoneType") to str
[Task Queue] Already waiting for 254.3488481999957S, seq=4
[Task Queue] Already waiting for 143.25238799999352S, seq=5
[Task Queue] Already waiting for 154.41364509999403S, seq=5
[Task Queue] Already waiting for 265.5101954000129S, seq=4
[Task Queue] Already waiting for 165.5822293999954S, seq=5
[Task Queue] Already waiting for 276.6787590000022S, seq=4

**Comment by 812913329** [comment]
@konieshadow   If the submission is too fast or there seems to be some issues with the submitted information, or if the submission end actively disconnects, this problem can occur. It keeps getting stuck in the previous task, and later submissions are waiting. After waiting for a long time, submitting again will automatically change the port

**Comment by 812913329** [comment]
找到原因了，更新后fooocus后好像就不会出现这种问题了。可以暂时不用管

**Comment by konieshadow** [comment]
我也发现了几个图片生成失败导致队列卡住的问题，已修复。谢谢反馈。
