### ISSUE TITLE
Issue with docker

### ISSUE THREAD

**Issue by rossman22590** [mrhan1993/Fooocus-API#41]
Traceback (most recent call last):
  File "/app/main.py", line 378, in <module>
    if prepare_environments(args):
  File "/app/main.py", line 224, in prepare_environments
    if not requirements_met(requirements_file):
  File "/app/main.py", line 130, in requirements_met
    import packaging.version

**Comment by konieshadow** [comment]
It should be fixed. Please update docker image using:
```
docker pull konieshadow/fooocus-api
```

Or using the latest tag: v0.3.6

**Comment by rossman22590** [comment]
how do i get txt to image to work? right now it doesn but launches fine and api is up

**Comment by konieshadow** [comment]
> how do i get txt to image to work? right now it doesn but launches fine and api is up

Can you open http://127.0.0.1:8888 ?

**Comment by konieshadow** [comment]
And cound you paste some output logs?

**Comment by rossman22590** [comment]
2023-11-03 23:08:51 Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
2023-11-03 23:08:51 Using pytorch attention in VAE
2023-11-03 23:08:51 missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection'}
2023-11-03 23:08:51 Base model loaded: /app/repositories/Fooocus/models/checkpoints/juggernautXL_version6Rundiffusion.safetensors
2023-11-03 23:08:51 LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.1), ('None', 0.1), ('None', 0.1), ('None', 0.1), ('None', 0.1)]
2023-11-03 23:08:51 Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
2023-11-03 23:08:51 Requested to load SDXLClipModel
2023-11-03 23:08:51 Requested to load GPT2LMHeadModel
2023-11-03 23:08:51 Loading 2 new models
2023-11-03 23:08:51 [Fooocus Model Management] Moving model(s) has taken 0.25 seconds
2023-11-03 23:08:51 INFO:     172.17.0.1:56778 - "POST /v1/generation/text-to-image HTTP/1.1" 500 Internal Server Error
2023-11-03 23:08:51 ERROR:    Exception in ASGI application
2023-11-03 23:08:51 Traceback (most recent call last):
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2023-11-03 23:08:51     result = await app(  # type: ignore[func-returns-value]
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2023-11-03 23:08:51     return await self.app(scope, receive, send)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
2023-11-03 23:08:51     await super().__call__(scope, receive, send)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
2023-11-03 23:08:51     await self.middleware_stack(scope, receive, send)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-11-03 23:08:51     raise exc
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-11-03 23:08:51     await self.app(scope, receive, _send)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2023-11-03 23:08:51     raise exc
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2023-11-03 23:08:51     await self.app(scope, receive, sender)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2023-11-03 23:08:51     raise e
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2023-11-03 23:08:51     await self.app(scope, receive, send)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
2023-11-03 23:08:51     await route.handle(scope, receive, send)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
2023-11-03 23:08:51     await self.app(scope, receive, send)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
2023-11-03 23:08:51     response = await func(request)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
2023-11-03 23:08:51     raw_response = await run_endpoint_function(
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
2023-11-03 23:08:51     return await run_in_threadpool(dependant.call, **values)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2023-11-03 23:08:51     return await anyio.to_thread.run_sync(func, *args)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
2023-11-03 23:08:51     return await get_asynclib().run_sync_in_worker_thread(
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2023-11-03 23:08:51     return await future
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-11-03 23:08:51     result = context.run(func, *args)
2023-11-03 23:08:51   File "/app/fooocusapi/api.py", line 88, in text2img_generation
2023-11-03 23:08:51     results = call_worker(req, accept)
2023-11-03 23:08:51   File "/app/fooocusapi/api.py", line 65, in call_worker
2023-11-03 23:08:51     results = process_generate(queue_task, params)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-11-03 23:08:51     return func(*args, **kwargs)
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-11-03 23:08:51     return func(*args, **kwargs)
2023-11-03 23:08:51   File "/app/fooocusapi/worker.py", line 35, in process_generate
2023-11-03 23:08:51     import fooocus_extras.preprocessors as preprocessors
2023-11-03 23:08:51   File "/app/repositories/Fooocus/fooocus_extras/preprocessors.py", line 1, in <module>
2023-11-03 23:08:51     import cv2
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
2023-11-03 23:08:51     bootstrap()
2023-11-03 23:08:51   File "/opt/venv/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
2023-11-03 23:08:51     native_module = importlib.import_module("cv2")
2023-11-03 23:08:51   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-11-03 23:08:51     return _bootstrap._gcd_import(name[level:], package, level)
2023-11-03 23:08:51 ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by rossman22590** [comment]
when i try to geenrate

**Comment by rossman22590** [comment]
<html>
<body>
<div class="btn-group" style="box-sizing: border-box; display: flex; padding: 30px; color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgba(73, 204, 144, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><button class="btn execute opblock-control__btn" style="font-family: sans-serif; font-size: 14px; line-height: 1.15; margin: 0px; overflow: visible; text-transform: none; appearance: button; cursor: pointer; background: rgb(73, 144, 226); border: 2px solid rgb(73, 144, 226); border-radius: 4px 0px 0px 4px; box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 2px; color: rgb(255, 255, 255); font-weight: 700; padding: 5px 23px; transition: all 0.3s ease 0s; flex: 1 1 0%;"><br class="Apple-interchange-newline">Execute</button><button class="btn btn-clear opblock-control__btn" style="font-family: sans-serif; font-size: 14px; line-height: 1.15; margin: 0px; overflow: visible; text-transform: none; appearance: button; cursor: pointer; background: transparent; border: 2px solid gray; border-radius: 0px 4px 4px 0px; box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 2px; color: rgb(59, 65, 81); font-weight: 700; padding: 5px 23px; transition: all 0.3s ease 0s; flex: 1 1 0%;">Clear</button></div><div class="responses-wrapper" style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgba(73, 204, 144, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="opblock-section-header" style="box-sizing: border-box; align-items: center; background: rgba(255, 255, 255, 0.8); box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 2px; display: flex; min-height: 50px; padding: 8px 20px;"><h4 style="box-sizing: border-box; color: rgb(59, 65, 81); flex: 1 1 0%; font-family: sans-serif; font-size: 14px; margin: 0px;">Responses</h4></div><div class="responses-inner" style="box-sizing: border-box; padding: 20px;"><div style="box-sizing: border-box;"><div style="box-sizing: border-box;"><div class="curl-command" style="box-sizing: border-box; position: relative;"><h4 style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: 12px; margin: 10px 0px 5px;">Curl</h4><div class="copy-to-clipboard" style="box-sizing: border-box; align-items: center; background: rgb(125, 130, 147); border: none; border-radius: 4px; bottom: 5px; display: flex; height: 20px; justify-content: center; position: absolute; right: 10px; width: 20px;"><button style="font-family: sans-serif; font-size: 16px; line-height: 1.15; margin: 0px; overflow: visible; text-transform: none; appearance: button; cursor: pointer; background: url(&quot;data:image/svg+xml;charset=utf-8,<svg xmlns=\&quot;http://www.w3.org/2000/svg\&quot; width=\&quot;16\&quot; height=\&quot;15\&quot; aria-hidden=\&quot;true\&quot;><path fill=\&quot;%23fff\&quot; fill-rule=\&quot;evenodd\&quot; d=\&quot;M4 12h4v1H4v-1zm5-6H4v1h5V6zm2 3V7l-3 3 3 3v-2h5V9h-5zM6.5 8H4v1h2.5V8zM4 11h2.5v-1H4v1zm9 1h1v2c-.02.28-.11.52-.3.7-.19.18-.42.28-.7.3H3c-.55 0-1-.45-1-1V3c0-.55.45-1 1-1h3c0-1.11.89-2 2-2 1.11 0 2 .89 2 2h3c.55 0 1 .45 1 1v5h-1V5H3v9h10v-2zM4 4h8c0-.55-.45-1-1-1h-1c-.55 0-1-.45-1-1s-.45-1-1-1-1 .45-1 1-.45 1-1 1H5c-.55 0-1 .45-1 1z\&quot;/></svg>&quot;) 50% center no-repeat; border: none; flex-grow: 1; flex-shrink: 1; height: 18px;"></button></div><div style="box-sizing: border-box;"><pre class="curl microlight" style="font-family: monospace; font-size: 12px; box-sizing: border-box; white-space: pre-wrap; overflow-wrap: break-word; background: rgb(51, 51, 51); border-radius: 4px; color: white; font-weight: 600; hyphens: auto; margin: 0px; padding: 0.5em; word-break: break-word; display: block; overflow-x: auto;"><code class="language-bash" style="font-family: Consolas, monaco, monospace; font-size: 1em; box-sizing: border-box; white-space: pre;"><span>curl -X </span><span style="color: rgb(162, 252, 162);">'POST'</span><span> \
</span><span>  </span><span style="color: rgb(162, 252, 162);">'http://127.0.0.1:8888/v1/generation/text-to-image'</span><span> \
</span><span>  -H </span><span style="color: rgb(162, 252, 162);">'accept: application/json'</span><span> \
</span><span>  -H </span><span style="color: rgb(162, 252, 162);">'Content-Type: application/json'</span><span> \
</span><span>  -d </span><span style="color: rgb(162, 252, 162);">'{
</span><span style="color: rgb(162, 252, 162);">  "prompt": "",
</span><span style="color: rgb(162, 252, 162);">  "negative_prompt": "",
</span><span style="color: rgb(162, 252, 162);">  "style_selections": [
</span><span style="color: rgb(162, 252, 162);">    "Fooocus V2",
</span><span style="color: rgb(162, 252, 162);">    "Fooocus Enhance",
</span><span style="color: rgb(162, 252, 162);">    "Fooocus Sharp"
</span><span style="color: rgb(162, 252, 162);">  ],
</span><span style="color: rgb(162, 252, 162);">  "performance_selection": "Speed",
</span><span style="color: rgb(162, 252, 162);">  "aspect_ratios_selection": "1152×896",
</span><span style="color: rgb(162, 252, 162);">  "image_number": 1,
</span><span style="color: rgb(162, 252, 162);">  "image_seed": -1,
</span><span style="color: rgb(162, 252, 162);">  "sharpness": 2,
</span><span style="color: rgb(162, 252, 162);">  "guidance_scale": 4,
</span><span style="color: rgb(162, 252, 162);">  "base_model_name": "juggernautXL_version6Rundiffusion.safetensors",
</span><span style="color: rgb(162, 252, 162);">  "refiner_model_name": "None",
</span><span style="color: rgb(162, 252, 162);">  "loras": [
</span><span style="color: rgb(162, 252, 162);">    {
</span><span style="color: rgb(162, 252, 162);">      "model_name": "sd_xl_offset_example-lora_1.0.safetensors",
</span><span style="color: rgb(162, 252, 162);">      "weight": 0.1
</span><span style="color: rgb(162, 252, 162);">    }
</span><span style="color: rgb(162, 252, 162);">  ],
</span><span style="color: rgb(162, 252, 162);">  "require_base64": false,
</span><span style="color: rgb(162, 252, 162);">  "async_process": false
</span><span style="color: rgb(162, 252, 162);">}'</span></code></pre></div></div><div style="box-sizing: border-box;"><div class="request-url" style="box-sizing: border-box;"><h4 style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: 12px; margin: 10px 0px 5px;">Request URL</h4><pre class="microlight" style="font-family: monospace; font-size: 12px; box-sizing: border-box; overflow-wrap: break-word; background: rgb(51, 51, 51); border-radius: 4px; color: rgb(255, 255, 255); font-weight: 600; hyphens: auto; margin: 0px; padding: 10px; white-space: pre-wrap; word-break: break-word;">http://127.0.0.1:8888/v1/generation/text-to-image</pre></div></div><h4 style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: 12px; margin: 10px 0px 5px;">Server response</h4>

Code | Details
-- | --
500Undocumented | Error: Internal Server ErrorResponse bodyDownloadInternal Server ErrorResponse headers content-length: 21  content-type: text/plain; charset=utf-8  date: Sat,04 Nov 2023 03:34:40 GMT  server: uvicorn

</div></div></div></div>
</body>
</html>

**Comment by konieshadow** [comment]
Looks like an error related OpenCV dependency of Docker image. Fixed in v0.3.8.

**Comment by rayadaschn** [comment]
The problem arises again in the current [v0.3.22](https://github.com/konieshadow/Fooocus-API/releases/tag/v0.3.22) release @konieshadow  :
```bash
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Fooocus-API version: 0.3.22
Git clone failed for Fooocus: failed to connect to github.com: Connection timed out
[Fooocus-API] Task queue size: 3, queue history size: 100
Traceback (most recent call last):
  File "/home/Fooocus-API/main.py", line 378, in <module>
    if prepare_environments(args):
  File "/home/Fooocus-API/main.py", line 286, in prepare_environments
    import modules.config as config
ModuleNotFoundError: No module named 'modules'
```

**Comment by rayadaschn** [comment]
🙏 This problem seems to have reappeared in [v0.3.22](https://github.com/konieshadow/Fooocus-API/releases/tag/v0.3.22):

When I run `python main.py`

```bash
[Fooocus-API] Task queue size: 3, queue history size: 100
Traceback (most recent call last):
  File "/home/Fooocus-API/main.py", line 378, in <module>
    if prepare_environments(args):
  File "/home/Fooocus-API/main.py", line 286, in prepare_environments
    import modules.config as config
ModuleNotFoundError: No module named 'modules'
```

👀 It seems that the server container can not access github, so how to use it in China? (PS. The server can connect to github.com (140.82.114.4))
